In [1]:
import numpy as np
from numba import jit

In [35]:
def python_matrix_K(n,m):
    K = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            K[i,j] = i + j
    return K

In [10]:
n = 10000
m = 6000
%time python_matrix_K(n,m)

CPU times: total: 7.33 s
Wall time: 7.75 s


array([[0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 5.9970e+03, 5.9980e+03,
        5.9990e+03],
       [1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 5.9980e+03, 5.9990e+03,
        6.0000e+03],
       [2.0000e+00, 3.0000e+00, 4.0000e+00, ..., 5.9990e+03, 6.0000e+03,
        6.0010e+03],
       ...,
       [9.9970e+03, 9.9980e+03, 9.9990e+03, ..., 1.5994e+04, 1.5995e+04,
        1.5996e+04],
       [9.9980e+03, 9.9990e+03, 1.0000e+04, ..., 1.5995e+04, 1.5996e+04,
        1.5997e+04],
       [9.9990e+03, 1.0000e+04, 1.0001e+04, ..., 1.5996e+04, 1.5997e+04,
        1.5998e+04]])

In [32]:
@jit(nopython=True)
def numba_matrix_K(n,m):
    K = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            K[i,j] = i + j
    return K

In [12]:
n = 10000
m = 60000
%time numba_matrix_K(n,m)

CPU times: total: 1.61 s
Wall time: 1.7 s


array([[0.0000e+00, 1.0000e+00, 2.0000e+00, ..., 5.9997e+04, 5.9998e+04,
        5.9999e+04],
       [1.0000e+00, 2.0000e+00, 3.0000e+00, ..., 5.9998e+04, 5.9999e+04,
        6.0000e+04],
       [2.0000e+00, 3.0000e+00, 4.0000e+00, ..., 5.9999e+04, 6.0000e+04,
        6.0001e+04],
       ...,
       [9.9970e+03, 9.9980e+03, 9.9990e+03, ..., 6.9994e+04, 6.9995e+04,
        6.9996e+04],
       [9.9980e+03, 9.9990e+03, 1.0000e+04, ..., 6.9995e+04, 6.9996e+04,
        6.9997e+04],
       [9.9990e+03, 1.0000e+04, 1.0001e+04, ..., 6.9996e+04, 6.9997e+04,
        6.9998e+04]])

In [28]:
def numpy_matrix_K(n,m):
    return np.outer(np.arange(n), np.arange(m)) + np.kron(np.ones(m), np.arange(n)).reshape((n,m))

In [40]:
n = 10000
m = 60000
%time numpy_matrix_K(n,m)

CPU times: total: 6.8 s
Wall time: 7.42 s


array([[0.00000000e+00, 1.00000000e+00, 2.00000000e+00, ...,
        9.99700000e+03, 9.99800000e+03, 9.99900000e+03],
       [0.00000000e+00, 2.00000000e+00, 4.00000000e+00, ...,
        6.99940000e+04, 6.99960000e+04, 6.99980000e+04],
       [0.00000000e+00, 3.00000000e+00, 6.00000000e+00, ...,
        1.29991000e+05, 1.29994000e+05, 1.29997000e+05],
       ...,
       [0.00000000e+00, 9.99800000e+03, 1.99960000e+04, ...,
        5.99800006e+08, 5.99810004e+08, 5.99820002e+08],
       [0.00000000e+00, 9.99900000e+03, 1.99980000e+04, ...,
        5.99860003e+08, 5.99870002e+08, 5.99880001e+08],
       [0.00000000e+00, 1.00000000e+04, 2.00000000e+04, ...,
        5.99920000e+08, 5.99930000e+08, 5.99940000e+08]])

In [39]:
print(numpy_matrix_K(10,6))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  8. 10. 12.  4.  6.]
 [ 2.  5.  8. 11. 14. 17.]
 [ 8. 12.  6. 10. 14. 18.]
 [ 4.  9. 14. 19. 24. 29.]
 [ 0.  6. 12. 18. 24. 30.]
 [ 6. 13. 20. 27. 24. 31.]
 [ 2. 10. 18. 26. 34. 42.]
 [ 8. 17. 16. 25. 34. 43.]
 [ 4. 14. 24. 34. 44. 54.]]


In [37]:
print(numba_matrix_K(10,6))

[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.  7.]
 [ 3.  4.  5.  6.  7.  8.]
 [ 4.  5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9. 10.]
 [ 6.  7.  8.  9. 10. 11.]
 [ 7.  8.  9. 10. 11. 12.]
 [ 8.  9. 10. 11. 12. 13.]
 [ 9. 10. 11. 12. 13. 14.]]


In [36]:
print(python_matrix_K(10,6))

[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.  7.]
 [ 3.  4.  5.  6.  7.  8.]
 [ 4.  5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9. 10.]
 [ 6.  7.  8.  9. 10. 11.]
 [ 7.  8.  9. 10. 11. 12.]
 [ 8.  9. 10. 11. 12. 13.]
 [ 9. 10. 11. 12. 13. 14.]]
